import type {
  ActivityItem,
  Project,
  ProjectTask,
  TeamMember,
} from "@/lib/types";

export const localToday = new Date("2026-07-04T12:00:00.000Z");

export const team: TeamMember[] = [
  {
    id: "member-1",
    name: "Amina Khan",
    initials: "AK",
    role: "Project lead",
    color: "#1f6b4f",
  },
  {
    id: "member-2",
    name: "Marcus Reed",
    initials: "MR",
    role: "Site supervisor",
    color: "#b96532",
  },
  {
    id: "member-3",
    name: "Sara Malik",
    initials: "SM",
    role: "Cost manager",
    color: "#5a57a6",
  },
  {
    id: "member-4",
    name: "Noah Williams",
    initials: "NW",
    role: "Architect",
    color: "#356c9b",
  },
];

function task(
  projectId: string,
  taskData: Omit<ProjectTask, "projectId">,
): ProjectTask {
  return { projectId, ...taskData };
}

const riversideTasks: ProjectTask[] = [
  task("riverside-villa", {
    id: "rv-1",
    type: "summary",
    title: "Site preparation",
    startDate: "2026-05-18",
    endDate: "2026-06-12",
    progress: 100,
    assigneeIds: ["member-2"],
    sortOrder: 1,
  }),
  task("riverside-villa", {
    id: "rv-2",
    parentId: "rv-1",
    type: "task",
    title: "Survey and setting out",
    startDate: "2026-05-18",
    endDate: "2026-05-22",
    progress: 100,
    assigneeIds: ["member-2", "member-4"],
    sortOrder: 2,
  }),
  task("riverside-villa", {
    id: "rv-3",
    parentId: "rv-1",
    type: "task",
    title: "Excavation and grading",
    startDate: "2026-05-25",
    endDate: "2026-06-12",
    progress: 100,
    assigneeIds: ["member-2"],
    sortOrder: 3,
  }),
  task("riverside-villa", {
    id: "rv-4",
    type: "summary",
    title: "Foundations",
    startDate: "2026-06-15",
    endDate: "2026-07-10",
    progress: 66,
    assigneeIds: ["member-1", "member-2"],
    sortOrder: 4,
  }),
  task("riverside-villa", {
    id: "rv-5",
    parentId: "rv-4",
    type: "task",
    title: "Footings and reinforcement",
    startDate: "2026-06-15",
    endDate: "2026-06-24",
    progress: 100,
    assigneeIds: ["member-2"],
    sortOrder: 5,
  }),
  task("riverside-villa", {
    id: "rv-6",
    parentId: "rv-4",
    type: "task",
    title: "Foundation walls",
    startDate: "2026-06-25",
    endDate: "2026-07-02",
    progress: 72,
    assigneeIds: ["member-2"],
    sortOrder: 6,
  }),
  task("riverside-villa", {
    id: "rv-7",
    parentId: "rv-4",
    type: "task",
    title: "Waterproofing and drainage",
    startDate: "2026-07-03",
    endDate: "2026-07-10",
    progress: 20,
    assigneeIds: ["member-1", "member-2"],
    sortOrder: 7,
  }),
  task("riverside-villa", {
    id: "rv-8",
    type: "summary",
    title: "Structural frame",
    startDate: "2026-07-13",
    endDate: "2026-08-28",
    progress: 0,
    assigneeIds: ["member-1"],
    sortOrder: 8,
  }),
  task("riverside-villa", {
    id: "rv-9",
    parentId: "rv-8",
    type: "task",
    title: "Ground-floor columns",
    startDate: "2026-07-13",
    endDate: "2026-07-24",
    progress: 0,
    assigneeIds: ["member-2"],
    sortOrder: 9,
  }),
  task("riverside-villa", {
    id: "rv-10",
    parentId: "rv-8",
    type: "task",
    title: "First-floor slab",
    startDate: "2026-07-27",
    endDate: "2026-08-07",
    progress: 0,
    assigneeIds: ["member-2"],
    sortOrder: 10,
  }),
  task("riverside-villa", {
    id: "rv-11",
    parentId: "rv-8",
    type: "task",
    title: "Roof structure complete",
    startDate: "2026-08-28",
    endDate: "2026-08-28",
    progress: 0,
    assigneeIds: ["member-1", "member-4"],
    sortOrder: 11,
  }),
];

export const projects: Project[] = [
  {
    id: "riverside-villa",
    code: "RV-026",
    name: "Riverside Villa",
    location: "Lahore",
    description:
      "A two-storey family home with a shaded courtyard and river-facing terrace.",
    startDate: "2026-05-18",
    endDate: "2026-12-18",
    budgetMinor: 46_500_000_00,
    spentMinor: 13_420_000_00,
    teamIds: ["member-1", "member-2", "member-3", "member-4"],
    tasks: riversideTasks,
    dependencies: [
      {
        id: "dep-1",
        sourceTaskId: "rv-2",
        targetTaskId: "rv-3",
        type: "finish_to_start",
      },
      {
        id: "dep-2",
        sourceTaskId: "rv-3",
        targetTaskId: "rv-5",
        type: "finish_to_start",
      },
      {
        id: "dep-3",
        sourceTaskId: "rv-5",
        targetTaskId: "rv-6",
        type: "finish_to_start",
      },
      {
        id: "dep-4",
        sourceTaskId: "rv-6",
        targetTaskId: "rv-7",
        type: "finish_to_start",
      },
      {
        id: "dep-5",
        sourceTaskId: "rv-7",
        targetTaskId: "rv-9",
        type: "finish_to_start",
      },
    ],
    updatedAt: "2026-07-04T08:45:00.000Z",
  },
  {
    id: "cedar-townhomes",
    code: "CT-014",
    name: "Cedar Townhomes",
    location: "Islamabad",
    description: "Six compact townhomes with shared landscaping and parking.",
    startDate: "2026-02-09",
    endDate: "2026-10-30",
    budgetMinor: 98_000_000_00,
    spentMinor: 47_800_000_00,
    teamIds: ["member-1", "member-2", "member-3"],
    tasks: [
      task("cedar-townhomes", {
        id: "ct-1",
        type: "task",
        title: "Block A masonry",
        startDate: "2026-06-01",
        endDate: "2026-06-30",
        progress: 82,
        assigneeIds: ["member-2"],
        sortOrder: 1,
      }),
      task("cedar-townhomes", {
        id: "ct-2",
        type: "task",
        title: "Block B services rough-in",
        startDate: "2026-06-22",
        endDate: "2026-07-17",
        progress: 45,
        assigneeIds: ["member-1", "member-2"],
        sortOrder: 2,
      }),
      task("cedar-townhomes", {
        id: "ct-3",
        type: "task",
        title: "Window package delivery",
        startDate: "2026-07-20",
        endDate: "2026-07-20",
        progress: 0,
        assigneeIds: ["member-1"],
        sortOrder: 3,
      }),
    ],
    dependencies: [],
    updatedAt: "2026-07-03T14:20:00.000Z",
  },
  {
    id: "northline-fitout",
    code: "NF-008",
    name: "Northline Office Fit-out",
    location: "Karachi",
    description: "A warm, low-energy workplace across two occupied floors.",
    startDate: "2026-04-06",
    endDate: "2026-08-14",
    budgetMinor: 31_000_000_00,
    spentMinor: 18_240_000_00,
    teamIds: ["member-1", "member-3", "member-4"],
    tasks: [
      task("northline-fitout", {
        id: "nf-1",
        type: "task",
        title: "Partition framing",
        startDate: "2026-06-08",
        endDate: "2026-06-26",
        progress: 100,
        assigneeIds: ["member-1"],
        sortOrder: 1,
      }),
      task("northline-fitout", {
        id: "nf-2",
        type: "task",
        title: "MEP first fix",
        startDate: "2026-06-29",
        endDate: "2026-07-10",
        progress: 55,
        assigneeIds: ["member-1"],
        sortOrder: 2,
      }),
      task("northline-fitout", {
        id: "nf-3",
        type: "task",
        title: "Ceiling grid",
        startDate: "2026-07-13",
        endDate: "2026-07-24",
        progress: 0,
        assigneeIds: ["member-4"],
        sortOrder: 3,
      }),
    ],
    dependencies: [],
    updatedAt: "2026-07-02T11:10:00.000Z",
  },
];

export const activity: ActivityItem[] = [
  {
    id: "activity-1",
    projectId: "riverside-villa",
    actorId: "member-2",
    action: "updated progress",
    detail: "Foundation walls moved from 60% to 72%.",
    targetType: "task",
    taskId: "rv-6",
    occurredAt: "2026-07-04T08:45:00.000Z",
  },
  {
    id: "activity-2",
    projectId: "cedar-townhomes",
    actorId: "member-1",
    action: "shifted a task",
    detail: "Block B services rough-in was extended by three days.",
    targetType: "task",
    taskId: "ct-2",
    occurredAt: "2026-07-03T14:20:00.000Z",
  },
  {
    id: "activity-3",
    projectId: "northline-fitout",
    actorId: "member-3",
    action: "recorded a cost",
    detail: "Electrical fixtures commitment added to the fit-out budget.",
    targetType: "budget",
    occurredAt: "2026-07-02T11:10:00.000Z",
  },
];

export function getProject(projectId: string) {
  return projects.find((project) => project.id === projectId);
}

export function getMember(memberId: string) {
  return team.find((member) => member.id === memberId);
}
